spring.application.name=taxiapp

spring.datasource.url=jdbc:postgresql://localhost:5432/taxidb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
